"""
Report Builder — generates the structured final medical report.
"""

from datetime import datetime


def build_report(
    symptoms: str,
    differential: list[dict],
    research_results: list[dict],
    user_answers: list[str],
    skeptic_critique: str,
) -> dict:
    if not isinstance(symptoms, str):
        symptoms = str(symptoms)
    if not isinstance(differential, list):
        differential = []
    if not isinstance(research_results, list):
        research_results = []
    if not isinstance(user_answers, list):
        user_answers = []
    if not isinstance(skeptic_critique, str):
        skeptic_critique = str(skeptic_critique)

    normalized_dx = []
    for item in differential:
        if not isinstance(item, dict):
            continue
        dx_item = dict(item)
        dx_item["confidence"] = _to_confidence(dx_item.get("confidence", 0))
        normalized_dx.append(dx_item)

    sorted_dx = sorted(normalized_dx, key=lambda d: d.get("confidence", 0), reverse=True)

    evidence_log = []
    for r in research_results:
        if not isinstance(r, dict):
            continue
        entry = {
            "title": r.get("title", "Source"),
            "url": r.get("url", ""),
            "snippet": r.get("snippet", ""),
        }
        full = r.get("full_content", "")
        if full:
            for dx in sorted_dx[:2]:
                condition = dx.get("condition", "").lower()
                sentences = full.split(".")
                for s in sentences:
                    if condition in s.lower() and len(s.strip()) > 30:
                        entry["key_quote"] = s.strip()[:300] + "."
                        break
        evidence_log.append(entry)

    top = sorted_dx[0] if sorted_dx else {}
    second = sorted_dx[1] if len(sorted_dx) > 1 else {}

    summary = (
        f"Based on the reported symptoms — {symptoms[:200]} — "
        f"the most likely diagnosis is **{top.get('condition', 'undetermined')}** "
        f"(confidence: {top.get('confidence', 'N/A')}%). "
    )
    if second:
        summary += (
            f"A secondary consideration is **{second.get('condition', '')}** "
            f"(confidence: {second.get('confidence', 'N/A')}%). "
        )
    if skeptic_critique:
        summary += f"Key clinical concern raised: {skeptic_critique[:200]}"

    next_steps = _generate_next_steps(sorted_dx, user_answers)

    return {
        "summary_of_findings": summary,
        "differential_diagnosis": sorted_dx,
        "evidence_log": evidence_log,
        "recommended_next_steps": next_steps,
        "metadata": {
            "generated_at": datetime.now().isoformat(),
            "questions_asked": len(user_answers),
            "sources_reviewed": len(research_results),
            "disclaimer": (
                "⚠️ This report is generated by an AI system for educational purposes only. "
                "It is NOT a substitute for professional medical advice, diagnosis, or treatment. "
                "Always consult a qualified healthcare provider."
            ),
        },
    }


def _generate_next_steps(differential: list[dict], user_answers: list[str]) -> list[str]:
    steps = [
        "Schedule an appointment with your primary care physician to discuss these findings.",
        "Bring a written list of your symptoms, including when they started and any triggers.",
    ]

    top_conditions = [d.get("condition", "").lower() for d in differential[:3]]

    condition_advice = {
        "migraine": "Consider keeping a headache diary noting triggers, duration, and severity.",
        "hypertension": "Monitor your blood pressure at home twice daily for one week.",
        "pneumonia": "Seek urgent care if you develop high fever, difficulty breathing, or chest pain.",
        "appendicitis": "⚠️ If you experience severe right lower abdominal pain, go to the ER immediately.",
        "anxiety": "Consider speaking with a mental health professional alongside your GP.",
        "gerd": "Avoid lying down for 2–3 hours after meals and limit acidic foods.",
        "urinary tract infection": "Stay well hydrated; avoid holding urine for extended periods.",
        "diabetes": "Request a fasting blood glucose test and HbA1c from your doctor.",
        "anemia": "Ask your doctor about a complete blood count (CBC) test.",
        "covid": "Consider getting tested and isolate until you have results.",
    }

    for condition_key, advice in condition_advice.items():
        if any(condition_key in c for c in top_conditions):
            steps.append(advice)

    steps.append(
        "If symptoms worsen suddenly or you experience chest pain, severe shortness of breath, "
        "loss of consciousness, or signs of a stroke, call emergency services immediately (911)."
    )

    return steps


def _to_confidence(value: object) -> int:
    if not isinstance(value, (int, float, str, bytes, bytearray)):
        return 0
    try:
        num = float(value)
    except (TypeError, ValueError):
        return 0
    return max(0, min(100, int(num)))
